#%RAML 1.0 ResourceType
   
description: Entity representing a <<resourcePathName|!singularize>>
get:
  description: |
    Get the <<resourcePathName|!singularize>>
    with <<resourcePathName|!singularize>>Id =
    {<<resourcePathName|!singularize>>Id}
  responses:
    200:
      body:
        application/json:
          type: <<exampleItem>>
          example: |
            <<exampleItem>>
    404:
      body:
        application/json:
          example: |
            <<example404>>

post:
  description: Create a new <<resourcePathName|!singularize>>
  responses:
        201:
          body:
            application/json:
              type: <<exampleItem>>
