#%RAML 1.0 ResourceType

description: Item <<resourcePathName>> in JSON format
uses:
  type: base.raml
get:
  responses:
    200:
      body:
        application/ld-json:
          example: |
            <<exampleitemjson>>
post:
  description: Create a new <<resourcePathName|!singularize>>
  responses:
        201:
          body:
            application/ld-json:
              type: <<itemJSONType>>
